Extract and error check container GID

diff --git a/jmaps b/jmaps
--- a/jmaps
+++ b/jmaps
@@ -81,7 +81,10 @@ for pid in $(pgrep -x java); do
 		tmpfile=$(mktemp -u)
 
 		container_pid=$(awk -F: '$1 == "NSpid" { print $2 }' /proc/$pid/status | awk '{ print $2 }')
-		nsenter="nsenter --target $pid --setuid $user --setgid $(nsenter --target $pid --mount --pid id -g $user) --mount --pid"
+
+		container_gid=$(nsenter --target $pid --mount --pid id -g $user) || (echo "Failed to get container GID" && continue)
+
+		nsenter="nsenter --target $pid --setuid $user --setgid $container_gid --mount --pid"
 
 		java_home=$(awk -F= 'BEGIN { RS = "\0" } $1 == "JAVA_HOME" { print $2 }' /proc/$pid/environ)
 		if [[ $java_home == "" ]]; then
